services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    environment:
      - DOCKER_API_VERSION=1.40
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - public-web

  app1:
    build: ./services/app1
    container_name: app1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app1.rule=Host(`app1.beshtawi.online`)"
      - "traefik.http.routers.app1.entrypoints=web"
      # Change 80 below if your internal app port is different (e.g., 3000)
      - "traefik.http.services.app1.loadbalancer.server.port=80"
    networks:
      - public-web

  app2:
    build: ./services/app2
    container_name: app2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app2.rule=Host(`app2.beshtawi.online`)"
      - "traefik.http.routers.app2.entrypoints=web"
      - "traefik.http.services.app2.loadbalancer.server.port=80"
    networks:
      - public-web

  main-app:
    build: ./services/default
    container_name: main-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.main-app.rule=Host(`beshtawi.online`)"
      - "traefik.http.routers.main-app.entrypoints=web"
      - "traefik.http.services.main-app.loadbalancer.server.port=80"
    networks:
      - public-web

networks:
  public-web:
    driver: bridge
